version: '3.6'
services:
  "aws-blog":
    build: ""
    image: 497680840552.dkr.ecr.ap-southeast-1.amazonaws.com/aws-blog:latest
    ports:
      - "8086:8086"
    volumes:
      - "./logs/aws-blog:/data/logs/aws-blog"
    restart: always
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        parallelism: 2
      restart_policy:
        condition: always

